server:
  port: 9003

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: project-Qa
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.77.145.221:3306/Project_DB?characterEncoding=utf-8&useSSL=true
    username: root
    password: 0

  rabbitmq:
    host: 120.77.145.221

  jpa:
    database: MySQL
    show-sql: true
#    generate-ddl: true

#   update:无表的时候根据entity创建表
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      
      #验证连接是否有效。此参数必须设置为非空字符串，下面三项设置成true才能生效
     validationQuery: SELECT 1
      #指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除.
     testWhileIdle: true
      #指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
     testOnBorrow: true
      #指明是否在归还到池中前进行检验
     testOnReturn: false
